language: elixir
elixir:
  - "1.8"
otp_release:
  - "21.0"
  
sudo: false

env:
  - MIX_ENV=test
  - COVERALLS_SERVICE_NAME=travis-ci

before_script:
  - "mix deps.get && mix compile"
  
script:
  - "mix coveralls.travis"